<?xml version='1.0' encoding='utf-8' standalone='no'?>
<!DOCTYPE issue SYSTEM "lwg-issue.dtd">

<issue num="4133" status="New">
<title><tt><i>awaitable-receiver</i></tt>'s members are potentially throwing</title>
<section><sref ref="[exec.as.awaitable]"/></section>
<submitter>Eric Niebler</submitter>
<date>30 Jul 2024</date>
<priority>1</priority>

<discussion>
<p>
The specification of <tt><i>awaitable-receiver</i></tt> in <sref ref="[exec.as.awaitable]"/>/p4 
as of <paper num="N4988"/> is not taking into consideration the fact that the <tt>resume()</tt> 
and <tt>promise()</tt> member functions on <tt>coroutine_handle&lt;P&gt;</tt> are not marked <tt>noexcept</tt>. 
<tt><i>awaitable-receiver</i></tt>'s member functions must all be <tt>noexcept</tt>, but they are 
specified as being "equivalent to" statement that call <tt>resume()</tt> and <tt>promise()</tt> 
outside of <tt>try</tt>/<tt>catch</tt> blocks.
</p>

<note>2024-08-21; Reflector poll</note>
<p>
Set priority to 1 after reflector poll.
</p>
<p>
`promise()` can probably be <i>Throws</i>: Nothing
(along with a bunch of other coroutine_handle members),
but `resume()` certainly can throw.
Also AS-EXCEPT-PTR can throw for the `error_code` case
(that might be worth a separate issue though).
</p>

</discussion>

<resolution>
</resolution>

</issue>
